baseurl = "https://ninkigumi.github.io/web-contents"
languageCode = "ja"
title = "My New Hugo Site"
disableHugoGeneratorInject = true
hasCJKLanguage = true

[Params]
GoogleAnalytics = "UA-46259108-6"
